language: python
python:
  - "2.7"
install:
  - pip install coveralls coverage
  - pip install -r requirements.txt --use-mirrors
script:
  - coverage run --source=spriter setup.py test
after_script:
  - coveralls
