language: python
python:
  - "2.7"
before_install:
 -  sudo apt-get install libjpeg-dev libpng-dev libtiff-dev
install:
  - pip install -r requirements-dev.txt --use-mirrors
  - pip install -r requirements.txt --use-mirrors
script:
  - coverage run --source=spriter setup.py test
after_script:
  - coveralls
